dom 09 mar 2025 12:09:48 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/pkgbuild/pkgbuild.install b/pkgbuild/pkgbuild.install
--- a/pkgbuild/pkgbuild.install
+++ b/pkgbuild/pkgbuild.install
@@ -18,17 +18,55 @@ export white="\033[1;37m"
 export bold="\033[1m"
 export reset="\033[0m"
 
+# ambiente atual
+declare IS_UPGRADE=false
+declare WM='template'
+declare pkgname=comm-"${WM}"
+
 msg() {
-	local msg="$1"
-	echo -e "${green}==>[comm-template] ${bold}${yellow}${msg}${reset}" >&2
+  local msg="$1"
+  echo -e "${green}==>[${pkgname}] ${bold}${yellow}${msg}${reset}" >&2
+}
+
+sh_load_optdepends() {
+	local info_file="/usr/share/${pkgname}/optdepends"
+
+	if [[ -f "$info_file" && -r "$info_file" ]]; then
+		mapfile -t OPTDEPENDS <"$info_file"
+	else
+		msg "${red}FATAL: Something went wrong! File '$info_file' not found or without read permission."
+		msg "${red}FATAL: Something went wrong! File '$info_file' not found or without read permission."
+	fi
+}
+
+sh_start_dbus_in_chroot() {
+	# Verifica se o D-Bus já está em execução
+	if ! pgrep -x "dbus-daemon" >/dev/null; then
+		# Cria o diretório para o socket do D-Bus
+		mkdir -p /run/dbus
+		chmod 755 /run/dbus
+
+		# Inicia o D-Bus
+		dbus-daemon --system --fork
+
+		# Configura as variáveis de ambiente
+		export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket
+		export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket
+	fi
 }
 
 post_install() {
-	msg "Initializing system configuration..."
+	msg "Initializing system installation and configuration..."
+
+	sh_load_optdepends
 
 	[[ -e /etc/environment ]] && source /etc/environment
 	: "${IN_CHROOT_INSTALLER:=false}"
 	: "${IN_CHROOT_INSTALLER_USER:=root}"
+
+	if $IN_CHROOT_INSTALLER; then
+		sh_start_dbus_in_chroot
+	fi
 
 	if [[ -f /var/lib/pacman/db.lck ]]; then
 		rm -f /var/lib/pacman/db.lck &>/dev/null
@@ -43,12 +81,22 @@ post_install() {
 		lib32-vulkan-mesa-layers
 	)
 
+	synchronizing_database() {
+		pacman -Sy --quiet --noconfirm &>/dev/null
+	}
+
 	install_packages() {
 		pacman -S --quiet --noconfirm --needed --overwrite \* "$@" &>/dev/null
 	}
 
+	msg "Please wait, synchronizing databases..."
+	synchronizing_database
+
 	msg "Installing common packages: ${COMMON_PACKAGES[*]}"
 	install_packages "${COMMON_PACKAGES[@]}"
+
+	msg "Installing optdepends packages: ${OPTDEPENDS[*]}"
+	install_packages "${OPTDEPENDS[@]}"
 
 	msg "Detecting GPU and installing appropriate drivers..."
 	GPU_INFO=$(lspci -nnk | grep -A3 -E "VGA|3D|Display")
@@ -97,11 +145,6 @@ EOF
 	mkdir -p /var/lib/lxdm >/dev/null
 	chown -R lxdm:lxdm /var/lib/lxdm >/dev/null
 
-	msg "Enabling Lxdm..."
-	if ! systemctl enable lxdm &>/dev/null; then
-		msg "${red}Error: It went wrong when activating lxdm"
-	fi
-
 	msg "Setting up user..."
 	user=$(awk -F: '$3 >= 1000 && $3 < 65000 { print $1; exit }' /etc/passwd)
 	if $IN_CHROOT_INSTALLER; then
@@ -125,29 +168,44 @@ EOF
 		msg "${yellow}Warning: Failed to compile Nautilus schemas. Some features may not work correctly.${reset}"
 	fi
 
-	if ! $IN_CHROOT_INSTALLER; then
-		msg "Please wait, Generating initramfs for all kernels..."
-		mkinitcpio -P &>/dev/null
-
-		msg "Configuring GRUB..."
-		# Change GRUB config
-		sed -i 's|^GRUB_CMDLINE_LINUX_DEFAULT=.*|GRUB_CMDLINE_LINUX_DEFAULT="quiet splash plymouth.enable=1 loglevel=4 libata.noacpi=1 acpi=force apm=power-off nowatchdog tsc=nowatchdog cryptomgr.notests no_timer_check rcupdate.rcu_expedited=1 intel_pstate=active amd_pstate=active cpuidle.governor=teo split_lock_detect=off clearcpuid=514 transparent_hugepage=never skew_tick=1 intremap=off nosoftlockup audit=0 nomce systemd.show_status=auto rd.udev.log_level=3 apparmor=1 security=apparmor vconsole.font=Uni2-Fixed16 intel_iommu=on amd_iommu=on tdx=on nvme_load=yes nouveau.modeset=1 i915.modeset=1 amdgpu.modeset=1 radeon.si_support=0 radeon.cik_support=0 amdgpu.si_support=1 amdgpu.cik_support=1 nvidia.modeset=1 nvidia_drm.modeset=1 DEEPIN_GFXMODE="|' /etc/default/grub >/dev/null
-
-		msg "Generating GRUB configuration files..."
-		update-grub &>/dev/null
+	if ! $IS_UPGRADE; then
+		msg "Enabling Lxdm..."
+		if ! systemctl enable lxdm &>/dev/null; then
+			msg "${red}Error: It went wrong when activating lxdm"
+		fi
 	fi
 
-	msg "Installation complete. Rebooting in 10 seconds..."
-	# Countdown before reboot
-	for i in $(seq 10 -1 1); do
-		printf "%d..." "$i"
-		sleep 1
-	done
-	echo
-	msg "Rebooting now..."
-	reboot
+	if ! $IN_CHROOT_INSTALLER; then
+		if ! $IS_UPGRADE; then
+			msg "Please wait, Generating initramfs for all kernels..."
+			mkinitcpio -P &>/dev/null
+
+			msg "Configuring GRUB..."
+			# Change GRUB config
+			sed -i "s/^GRUB_DISTRIBUTOR=\"\(.*\)\"/GRUB_DISTRIBUTOR=\"\1 ${WM}\"/" /etc/default/grub 1>/dev/null
+			sed -i 's|^GRUB_CMDLINE_LINUX_DEFAULT=.*|GRUB_CMDLINE_LINUX_DEFAULT="quiet splash plymouth.enable=1 loglevel=4 libata.noacpi=1 acpi=force apm=power-off nowatchdog tsc=nowatchdog cryptomgr.notests no_timer_check rcupdate.rcu_expedited=1 intel_pstate=active amd_pstate=active cpuidle.governor=teo split_lock_detect=off clearcpuid=514 transparent_hugepage=never skew_tick=1 intremap=off nosoftlockup audit=0 nomce systemd.show_status=auto rd.udev.log_level=3 apparmor=1 security=apparmor vconsole.font=Uni2-Fixed16 intel_iommu=on amd_iommu=on tdx=on nvme_load=yes nouveau.modeset=1 i915.modeset=1 amdgpu.modeset=1 radeon.si_support=0 radeon.cik_support=0 amdgpu.si_support=1 amdgpu.cik_support=1 nvidia.modeset=1 nvidia_drm.modeset=1 DEEPIN_GFXMODE="|' /etc/default/grub 1>/dev/null
+
+			msg "Generating GRUB configuration files..."
+			update-grub &>/dev/null
+		fi
+	fi
+
+	if ! $IS_UPGRADE; then
+		msg "Installation complete. Rebooting in 10 seconds..."
+		# Countdown before reboot
+		for i in $(seq 10 -1 1); do
+			printf "%d..." "$i"
+			sleep 1
+		done
+		echo
+		msg "Rebooting now..."
+		reboot
+	else
+		msg "Upgrade complete."
+	fi
 }
 
 post_upgrade() {
+	IS_UPGRADE=true
 	post_install
 }
